# ==============================
# Common (shared across all env)
# ==============================
spring:
  application:
    name: auth-service

springdoc:
  swagger-ui:
    path: /swagger-ui.html

# ===================================
# LOCAL PROFILE
# ===================================
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/AuthDB
    username: abderrahmane
    password: abderrahmane

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      properties:
        spring.json.trusted.packages: "*"
    topic:
      name: user-registration

server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


# ===================================
# DOCKER PROFILE
# ===================================
---
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/


# ===================================
# KUBERNETES PROFILE
# ===================================
---
spring:
  config:
    activate:
      on-profile: k8s
