# ==============================
# Common (shared across all env)
# ==============================
spring:
  application:
    name: user-service

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info

# ===================================
# LOCAL PROFILE
# ===================================
---
spring:
  config:
    activate:
      on-profile: local

  data:
    mongodb:
      uri: mongodb://localhost:27018/UsersDB

  jpa:
    hibernate:
      ddl-auto: create-drop

  kafka:
    bootstrap-servers: localhost:9092
    topic:
      name: user-registration
    consumer:
      group-id: user-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest # from beginning if no offset is present
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


# ===================================
# DOCKER PROFILE
# ===================================
---
spring:
  config:
    activate:
      on-profile: docker

  data:
    mongodb:
      uri: mongodb://mongo_users:27017/UsersDB

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/


# ===================================
# KUBERNETES PROFILE
# ===================================
---
spring:
  config:
    activate:
      on-profile: k8s
