# ==============================
# Common (shared across all env)
# ==============================
spring:
  application:
    name: user-service

  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /swagger-ui.html

  data:
    mongodb:
      uri: mongodb://localhost:27017/UsersDB

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info

# ===================================
# LOCAL PROFILE (no Docker)
# ===================================
---
spring:
  config:
    activate:
      on-profile: local

  server:
    port: 8085

  data:
    mongodb:
      uri: mongodb://localhost:27018/UsersDB

  jpa:
    hibernate:
      ddl-auto: create-drop

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


# ===================================
# DOCKER PROFILE
# ===================================
---
spring:
  config:
    activate:
      on-profile: docker

  data:
    mongodb:
      uri: mongodb://mongo_users:27017/UsersDB

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/


# ===================================
# KUBERNETES PROFILE
# ===================================
---
spring:
  config:
    activate:
      on-profile: k8s
